FROM nvidia/cuda-ppc64le:8.0-devel-ubuntu16.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y build-essential git cmake

RUN git clone https://github.com/ethereum-mining/ethminer /ethminer

WORKDIR /ethminer
RUN git checkout tags/v0.12.0

WORKDIR /ethminer/build

#RUN apt-cache search opencl
#RUN apt-get install -y nvidia-opencl-icd-384 nvidia-opencl-dev

RUN cmake .. -DETHASHCUDA=ON -DETHSTRATUM=ON -DETHASHCL=OFF
RUN make
RUN make install

